### ISSUE TITLE
Logout without seeing the webpage

### ISSUE THREAD

**Issue by selvananbu** [vmurin/react-native-azure-auth#119]
I wanted to logout without seeing the webpage.Currently when i logout from my app it goes to webpage and asks user to logout from there as well but want to skip this step can we do it ?

**Comment by vmurin** [comment]
unfortunately it's not possible. We have to go to logout page and additional question from MS can not be switched off.

See MS documentation [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-a-sign-out-request) and [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-sign-in?tabs=aspnetcore)

Quote from the docs:

_f your app didn't go to the logout endpoint, the user will reauthenticate to your app without entering their credentials again. The reason is that they'll have a valid single sign-in session with the Microsoft identity platform._

**Comment by selvananbu** [comment]
Thanks for your reply
