### ISSUE TITLE
Need admin Approval

### ISSUE THREAD

**Issue by selvananbu** [vmurin/react-native-azure-auth#120]
Hi ,
   I am using the Azure login for my app im getting the following consent screen i checked my azure account settings but the setting looks good because when i tried to login using same user id in another native android app there seems to be no issue can you help me on this.

If the user is inside a group then im facing this issue.But for the same user if i tried to login using another native app it works fine.
   
![Screenshot_1622557570](https://user-images.githubusercontent.com/5378843/120340327-8c441880-c313-11eb-8039-8fbde34c99ff.png)

**Comment by vmurin** [comment]
Hi, 

obviously you are using some corporate account. You have also registered your app in the same account. Right? So your app is obliged the corporate rules as well. This rules can limit access to some possibilities.

If you are using the same account in some another app - this app is registered in another account and is obliged to another rules - that's why it can work with your account...

Check what permissions your registered app is requiring, is there some not needed. Try to reduce the permission set to bare minimum. And the last try - just register a new privat MS account and create the app registration there.
