### ISSUE TITLE
Can't use SingleTask

### ISSUE THREAD

**Issue by ntvinhit** [vmurin/react-native-azure-auth#15]
I use launchMode="singleTop" for "react-native-google-signin" and "react-native-firebase".
If I use launchMode="singleTask", those functions can't work.
How can I use this with singleTop launchMode?

**Comment by vmurin** [comment]
The app opens new browser tab intent to do Azure login and then this Tab get redirected to the URLScheme defined as our app prefix, in other words not new http(s) address will be opened but our app from where we have called the new browser tab. In the app we have an URL Listener that intercepts the redirect and exchanges the auth code from URL with auth token. 
Therefore we need that our initial activity where the URL Listener is set up to be called. It ist granted due to "singleTask" mode.

The difference to google affiliated libraries is that they are using native clients to sign in, and for Azure the browser tab and "normal" web sign in is used.

What you could do:
1) try to use "singleTop" mode for main activity and see whether it works
2) try to split your app into activities and use "singleTask" only for Azure auth one.  (not sure how it can be accomplished with react native) 

Sorry if it does not help. 
Otherwise this is the limitation of the current solution.

**Comment by ntvinhit** [comment]
Thank you for your help. I tried with singleTop and it didn't work.
I tried with singleInstance then it works with both "react-native-google-signin" and "react-native-azure-auth", but not works with notification.
I will be digging it deeper.
