### ISSUE TITLE
Can id_token be bypassed when making the authorisation request?

### ISSUE THREAD

**Issue by Leli1024** [vmurin/react-native-azure-auth#169]
I keep getting stuck on the following line `let tokens = await azureAuth.webAuth.authorize({scope: 'openid profile User.Read' });`

Whenever I do a test log in I will receive the error: response type id_token is not enabled for the application. The issue is that I'm afraid enabling id_token will cause problems with the rest of the login portals for this application that are already live.

According to a colleague the issue could stem from the directory being referenced not being B2C but I haven't seen anything in this library indicating that's the case

**Comment by vmurin** [comment]
The error message means - you have not enabled openid or id token in Azure Portal by registering the app.
See paragraph 11. in the README [section ](https://github.com/vmurin/react-native-azure-auth#app-registration) **"App Registration"**

**Comment by aymather** [comment]
I'm running into the same issue, but like @Leli1024 I'm not sure that I am allowed to enable that setting. Is this a required setting in order to use this package? All I've seen in the documentation is "do this because well... do this" but I'm not entirely sure why/if it's required/what other alternatives are?

I was able to authenticate with a different package without this setting being active so I doubt it's "required" here. Unfortunately that other package no longer works so I'm searching for an alternative :/

**Comment by vmurin** [comment]
"do this because ... " - it is a core part of implemented Open ID Connect protocol :)
See the MS docs - https://learn.microsoft.com/en-us/azure/active-directory/develop/id-tokens

Actually it would be possible to disable "Open ID Connect" and leave the pure OAuth2. The only little change required in the library is to remove the hardcoded scope "openid". In the moment of writing I thought - everyone needs ID token and it disturb no one ;)

**Comment by aymather** [comment]
Yeah you should definitely leave this to the user. For example, all I care about in my app is authorization, and according to the documentation you provided... 

> ID tokens are intended to be understood by third-party applications. ID tokens should not be used for authorization purposes.

I figured out my issue with the other package which is `react-native-app-auth` and I'm now able to get all the functionality I need with that package (i.e. authorizing a user with azure & acquiring an access token) without having changed the `id_token` setting in the UI.

The `id_token` setting, _is_ a "setting" after all :)

**Comment by vmurin** [comment]
The OpenID Connect suppert is an essential part of this library. The setting to support "ID tokens" is safe ;)  as the `autorization_code ` grant is still used. So I will close this issue propose the solution from my comment above.
