### ISSUE TITLE
Cannot find 'redirect_uri'

### ISSUE THREAD

**Issue by malith-gammanpila** [vmurin/react-native-azure-auth#20]
I just implemented react-native-azure-auth in my react native project referring [react-native-azure-auth-sample](https://github.com/vmurin/react-native-azure-auth-sample) and when I tap on the Login button, it says
> AADSTS90102: 'redirect_uri' value must be a valid absolute Uri

on login.microsoftonline.com

I searched for a redirect_uri on the example implementation found in [react-native-azure-auth-sample](https://github.com/vmurin/react-native-azure-auth-sample). But I did not get anything. Help me, please.

**Comment by vmurin** [comment]
Hi Malith,

look at this read.me section  https://github.com/vmurin/react-native-azure-auth#callback-urls

Here is described the structure of callback URL or redirect URI (it is the same)

You should provide it by app registering on the MS APP page (see readme)
By me it was like this (for android):
**_com.auth.react://com.auth.react/android/callback_**

Please use your own YOUR_APP_PACKAGE_NAME (android)  instead of **com.auth.react** and YOUR_BUNDLE_IDENTIFIER (for iOS)
Actually it could be the same URI for both systems, but it seems to be the best practice to separate it.

Greets
Vladi

**Comment by malith-gammanpila** [comment]
> Hi Malith,
> 
> look at this read.me section https://github.com/vmurin/react-native-azure-auth#callback-urls
> 
> Here is described the structure of callback URL or redirect URI (it is the same)
> 
> You should provide it by app registering on the MS APP page (see readme)
> By me it was like this (for android):
> **_com.auth.react://com.auth.react/android/callback_**
> 
> Please use your own YOUR_APP_PACKAGE_NAME (android) instead of **com.auth.react** and YOUR_BUNDLE_IDENTIFIER (for iOS)
> Actually it could be the same URI for both systems, but it seems to be the best practice to separate it.
> 
> Greets
> Vladi

Hello @vmurin ,
Thank you very much for the information. Which file do I need to modify with these credentials? AndroidManifest.xml?

**Comment by vmurin** [comment]
No, as said, go to you APP registration under https://apps.dev.microsoft.com
And add redirect URI in stated format. See example screenshot (all values are only examples)
![2019-04-19_155153](https://user-images.githubusercontent.com/9309490/56427294-a2212b80-62bb-11e9-8d6f-2e0325e6d367.jpg)

Important that the package name in AndroidManifest.xml is exactly the same as you put in for redirect URI and the structure is correct, as the library relies on this structure. See [here](https://github.com/vmurin/react-native-azure-auth/blob/master/src/auth/index.js#L31)
