### ISSUE TITLE
Pass extra params to login url and exchange code functions

### ISSUE THREAD

**Issue by Harish-Duppalapudi** [vmurin/react-native-azure-auth#224]
Hi @vmurin, This package is very useful to fulfill my requirements and also supports a lot customizations.

 I'm working on the Azure AD login flow using an embedded web view, and I'm retrieving the login URL from `loginUrl()`.

According to the Azure documentation linked below, I must include additional fields such as `code_challenge_method`,` code_challenge`, `nonce`, and `response_mode` for enhanced security. Is there a way to pass these fields to `loginUrl()`?

[Azure AD Documentation Link](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow#request-an-authorization-code)

After getting the code from the Azure AD authorized. I'm using the `exchange()` function to get the token but was getting the error message that 'code_verifier' is required. 

After doing a lot of analysis, I found the issue.

- In the index.d.ts file, we allow to pass only the below parameters as shown in the image.

![image](https://github.com/user-attachments/assets/40680007-1dfa-481c-b405-8ad1ed2eb066)

- But in the implementation of that method, it is looking for the `code_verifier` parameter as required.

![image](https://github.com/user-attachments/assets/ca47e62f-a70b-403d-b276-e69b6731a8e5)

Can you add the `code_verifier` parameter in the index.d.ts file as well?

**React native version:** `0.75.3`.
**Script:** `Typescript`.
**Package version:** `1.8.9`

**Comment by vmurin** [comment]
Hi @Harish-Duppalapudi,

just use public function `authorize` instead of internal `exchange`. All mentioned by you parameters are set there. Look into source code: [link](https://github.com/vmurin/react-native-azure-auth/blob/fbccd8e1e0d90f9fc0e061abfce539b0534c4632/src/webauth/index.js#L53)

Also take a look on [sample app](https://github.com/vmurin/react-native-azure-auth-sample/blob/3326769d5d2bef8124948b51fdc8b43946fd2a8c/App.js#L29) how to call `authorize` and [docs](https://vmurin.github.io/react-native-azure-auth/WebAuth.html#.authorize)

**Comment by Harish-Duppalapudi** [comment]
Hi @vmurin, authorize is calling the external browser. but I'm trying to do the authorization using the embedded web view by the app itself.

**Comment by vmurin** [comment]
Just follow the same logic from source code [link](https://github.com/vmurin/react-native-azure-auth/blob/fbccd8e1e0d90f9fc0e061abfce539b0534c4632/src/webauth/index.js)
