### ISSUE TITLE
Logout callback on Android is not working.

### ISSUE THREAD

**Issue by gcsawargi** [vmurin/react-native-azure-auth#36]
iOS Callback on Logout in sample app works. But the browser tab on Android does not close on its own and does not invoke the logout callback. Any idea what I am doing wrong?

```
  _onLogout = () => {
    azureAuth.webAuth
      .clearSession({})
      .then(success => {
       //This does not get called on Android.
        this.setState({ accessToken: null, user: null });
      })
      .catch(error => console.log(error));
  };

```

**Comment by vmurin** [comment]
Please update to 1.1.5 and try again. I have just added default post logout URL - that should help to close the browser tab on android. 
But the real cause thou is the limitation of android platform - here we do not have `onLoaded` event for custom browser tab and have no native implementation for `hide()` method. That's why on iOS all works without changes.

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#send-a-sign-out-request
According to this docs the logout page should be closed now and the app returns back.

Feel free to reopen issue is the problem persists.
