### ISSUE TITLE
'React/RCTDefines.h' file not found

### ISSUE THREAD

**Issue by oscarCant17** [vmurin/react-native-azure-auth#63]
Hi,

I'm trying to use the package in iOS, but when I try to build it always crashes with this error **'React/RCTDefines.h'.**

I have tried in Android and works fine. However, in iOS I have done the links, and followed the config steps, but It doesn't works.

The error is in the **AzureAuth.h** file: 

`/react-native/React/Base/RCTBridgeModule.h:10:9: 'React/RCTDefines.h' file not found` where it tries the import `#import "RCTBridgeModule.h"`
 

`react: 16.8.3`
`react-native: 0.59.10`
`react-native-azure-auth: 1.3.10`

**Comment by vmurin** [comment]
Hi Oscar,

it should be some [auto]linking issue not directly related to the library (AzureAuth)
Take a look at the similar issues on github and stackoverflow:

https://github.com/oblador/react-native-store-review/issues/28
https://github.com/beefe/react-native-picker/issues/297
https://stackoverflow.com/questions/58373425/react-rctdefines-h-file-not-found-rn0-61

I will close the issue here as "not related".

Kind regards
Vladimir

**Comment by oscarCant17** [comment]
Thank you Vladimir,

Just realised that the pod wasn't being added to the podfile with `react-native link react-native-azure-auth`.

Just added `pod 'AzureAuth', :path => '../node_modules/react-native-azure-auth/ios` and now works.

**Comment by vmurin** [comment]
Perfect!
Thanks for the feedback!
