### ISSUE TITLE
Why this library uses implicit grant flow?

### ISSUE THREAD

**Issue by vladamx** [vmurin/react-native-azure-auth#88]
Hi, first of all thank you for making this library. It is really helpful.
My question is why have you decided to go with implicit flow rather than [authorization code flow](https://docs.microsoft.com/en-us/azure/active-directory-b2c/authorization-code-flow )
which is recommended for native apps.

**Comment by vmurin** [comment]
It is not true. 
Take a look at the [source code](https://github.com/vmurin/react-native-azure-auth/blob/fe6bacb273be8ee041213ea95be2e455e74e91a1/src/auth/index.js#L122). 

The library uses authorization code flow and it's also clearly stated at the very beginning of README.md file :)

If you was irritated by mentioning the implicit grant in the _App Registration_ section of the README - it only allows the Azure to answer on implicit grant request for registered app but not prescribe it and also do not affect the way how library works. The implicit grant could be used for some tests involving web application.

**Comment by vladamx** [comment]
Thank you for answering.

Microsoft recommends making this request for getting auth code by stating **&response_type=code**, instead of  **&response_type=code%20id_token**.  
I had problems with integration because of **&response_type=code%20id_token**. 
I can only enable both tokens when Implicit flow is used. 

Maybe I am missing something.

**Comment by vmurin** [comment]
Hey, thanks for clarification - now I see what you mean. 
The library allows besides authorization also authentication via OpenID Connect (OAuth2 extension) - see https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc

It's not implicit grant just OIDConnect requires `id_token` in the `response_type`. 
How it is handled in Azure internally I don't know. Probably due to this requirement the section Implicit Grant in the App Registration should be used. 
Obviously OIDConnect does not work without it.

> I can only enable both tokens when Implicit flow is used.
Do your mean in App Registration settings?

Actually the OpenID Connect feature could be made optional. I can check how much effort it needs...
